image: registry.gitlab.com/aaronrenner/docker-asdf

variables:
  LANG: C.UTF-8
  MIX_HOME: "$CI_PROJECT_DIR/.mix"
  ASDF_DATA_DIR: "$CI_PROJECT_DIR/.asdf"

stages:
  - install
  - build
  - test

before_script:
  - . ~/.asdf/asdf.sh
  # Ensure the timestamp doesn't change from when the repo was
  # originally checked out, so we don't have to recompile for each job.
  - |
    if [ -f ".cloned_at" ]; then
      git ls-files | xargs touch --date "$(cat .cloned_at)";
    fi

install_asdf_env_and_deps:
  stage: install
  cache:
    key: install
    paths:
      - $ASDF_DATA_DIR
      - $MIX_HOME
  script:
    - asdf plugin-add erlang || true
    - asdf plugin-add elixir || true
    # Have to run twice due to: https://github.com/asdf-vm/asdf-erlang/issues/57
    - asdf install && asdf install
    - mix local.hex --force
    - mix local.rebar --force
    # Cache the timestamp the repo was originally checked out, so it can
    # be set back to this in later jobs and allows us to skip unnecessary
    # recompiles.
    - stat -c "%y" README.md > .cloned_at
  artifacts:
    expire_in: 2 hrs
    paths:
      - $ASDF_DATA_DIR
      - $MIX_HOME
      - .cloned_at

.build:
  stage: build
  cache:
    key: $CI_JOB_NAME
    paths:
      - "*/_build"
      - "*/deps"
  script:
    - make install_deps compile
  dependencies:
    - install_asdf_env_and_deps
  artifacts:
    expire_in: 2 hrs
    paths:
      - "*/_build"
      - "*/deps"

build:dev:
  extends: .build

build:test:
  extends: .build
  variables:
    MIX_ENV: test

unit_tests:
  stage: test
  script: make test
  dependencies:
    - install_asdf_env_and_deps
    - build:test

linters:
  stage: test
  script:
    - make check_format
    - make check_unused_deps
  dependencies:
    - install_asdf_env_and_deps
    - build:dev

dialyzer:adafruit_io_http_client:
  stage: test
  variables:
    DIALYZER_ADAFRUIT_IO_HTTP_CLIENT_CACHE_VERSION: 1
  # --format short can't be used here due to: https://github.com/jeremyjh/dialyxir/issues/314
  # --list-unused-filters must be used as a command line option instead of in
  #      mix.exs due to: https://github.com/jeremyjh/dialyxir/issues/313
  script: make dialyzer_adafruit_io_http_client
  cache:
    key: $CI_JOB_NAME-$DIALYZER_ADAFRUIT_IO_HTTP_CLIENT_CACHE_VERSION
    paths:
      - "*/_build/dev/*.plt"
      - "*/_build/dev/*.plt.hash"
      - $MIX_HOME/*.plt
  dependencies:
    - install_asdf_env_and_deps
    - build:dev

dialyzer:freezer_eye:
  stage: test
  variables:
    DIALYZER_FREEZER_EYE_CACHE_VERSION: 1
  # --format short can't be used here due to: https://github.com/jeremyjh/dialyxir/issues/314
  # --list-unused-filters must be used as a command line option instead of in
  #      mix.exs due to: https://github.com/jeremyjh/dialyxir/issues/313
  script: make dialyzer_freezer_eye
  cache:
    key: $CI_JOB_NAME-$DIALYZER_FREEZER_EYE_CACHE_VERSION
    paths:
      - "*/_build/dev/*.plt"
      - "*/_build/dev/*.plt.hash"
      - $MIX_HOME/*.plt
  dependencies:
    - install_asdf_env_and_deps
    - build:dev
